language: generic
sudo: required
services: 
  - docker
befor_install:
  - docker build -t cherno/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true cherno/react-test npm test

after_success:
   - docker build -t chernoben/multi-container-client-project ./client
   - docker build -t chernoben/multi-container-nginx-project ./nginx
   - docker build -t chernoben/multi-container-server-project ./server
   - docker build -t chernoben/multi-container-worker-project ./worker
   # Log in to docker CLI
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   # pushing images to the dockerhub
   - docker push chernoben/multi-container-client-project
   - docker push chernoben/multi-container-nginx-project
   - docker push chernoben/multi-container-server-project
   - docker push chernoben/multi-container-worker-project